pub mod analyzer;
pub mod badge;
pub mod cost;
pub mod discovery;
pub mod explainer;
pub mod flaky_detector;
pub mod graph;
pub mod health_score;
pub mod linter;
pub mod mcp;
pub mod migration;
pub mod multi_repo;
pub mod optimizer;
pub mod parser;
pub mod plugins;
pub mod policy;
pub mod providers;
pub mod redact;
pub mod runner_sizing;
pub mod sbom;
pub mod security;
pub mod signing;
pub mod simulator;
pub mod test_selector;
pub mod whatif;

pub use analyzer::report::{AnalysisReport, Finding, Severity};
pub use flaky_detector::{FlakyCategory, FlakyDetector, FlakyReport, FlakyTest};
pub use linter::{lint, LintReport};
pub use migration::{github_actions_to_gitlab_ci, MigrationResult};
pub use multi_repo::{analyze_multi_repo, MultiRepoReport, RepoPipeline};
pub use optimizer::Optimizer;
pub use parser::argo::ArgoWorkflowsParser;
pub use parser::aws_codepipeline::AwsCodePipelineParser;
pub use parser::azure::AzurePipelinesParser;
pub use parser::bitbucket::BitbucketParser;
pub use parser::buildkite::BuildkiteParser;
pub use parser::circleci::CircleCIParser;
pub use parser::dag::{DagEdge, JobNode, PipelineDag, StepInfo};
pub use parser::drone::DroneParser;
pub use parser::github::GitHubActionsParser;
pub use parser::gitlab::GitLabCIParser;
pub use parser::jenkins::JenkinsParser;
pub use parser::tekton::TektonParser;
pub use plugins::{
    list_external_optimizer_plugins, run_external_analyzer_plugins, scaffold_manifest,
};
pub use policy::{check_policy, load_policy, PolicyConfig, PolicyReport};
pub use runner_sizing::{profile_pipeline as profile_runner_sizing, RunnerSizingReport};
pub use sbom::generate_sbom;
pub use security::scan as security_scan;
pub use signing::{generate_keypair, sign_report, verify_report};
pub use test_selector::{TestSelection, TestSelector, TestSelectorConfig};
