# BEFORE: Slow Node.js pipeline (31 minutes)
# Issues:
# - No caching (3 min wasted per run)
# - Serial execution (could save 12 min with parallelization)
# - Full clone (40 seconds wasted)
# - Running all tests on docs changes
# - Docker build not optimized (7 min wasted)

name: Node.js CI (UNOPTIMIZED)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Sequential dependency installation (3 min)
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install  # No cache - reinstalls every time!

  # Lint must wait for install (2 min)
  lint:
    runs-on: ubuntu-latest
    needs: [install]  # Unnecessary dependency
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install  # Installing again!
      - run: npm run lint

  # Build must wait for lint (6 min)
  build:
    runs-on: ubuntu-latest
    needs: [lint]  # Unnecessary dependency
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install  # Installing AGAIN!
      - run: npm run build

  # Unit tests must wait for build (8 min)
  test-unit:
    runs-on: ubuntu-latest
    needs: [build]  # Don't actually need build artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install  # Installing for the 4th time!
      - run: npm test  # Runs ALL 1,200 tests

  # E2E tests must wait for unit tests (12 min)
  test-e2e:
    runs-on: ubuntu-latest
    needs: [test-unit]  # Unnecessary dependency
    steps:
      - uses: actions/checkout@v4  # Full clone with entire git history
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install  # 5th time installing!
      - run: npm run test:e2e  # Single-threaded

  # Docker build (7 min)
  docker:
    runs-on: ubuntu-latest
    needs: [test-e2e]
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t myapp .  # No layer caching!

  # Deploy must wait for everything
  deploy:
    runs-on: ubuntu-latest
    needs: [docker, test-e2e, test-unit, lint]  # Waits for EVERYTHING
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying..."

# Total time: ~31 minutes
# Compute cost per run: $2.48 (31 min × $0.008/min)
# With 100 runs/month: $248/month
# Developer time wasted: 51.6 hours/month (for 10 devs, 10 runs/week each)
